#This file defines the minimum role required to access the specified URLs used in the web application. 
#There are three pre-defined roles:
       #Unauthenticated - URLs which can be accessed by everyone, even if the user is not authenticated in the system.
       #User - URLs which can be accessed only by users that passed the ApplinX authentication process.
       #Admin - URLs which can be accessed only by users granted "Admin" role through the ApplinX authentication process.
#URLs not defined in this file can be accessed only by role type "User".
#To define a URL, it should contain only the relative path to the resources of the application, prefixed with a "/" sign (not the full path).
#Example: for URL www.abc.com/resource.jsp, specify "/resource.jsp", or specify "/*.jsp" for all jsp files.
/index.jsp=Unauthenticated
/z_resourceReader.jsp=Unauthenticated
/run_printlet.jsp=Unauthenticated
/z_admin/z_editConfig.jsp=Admin
/config/*=Admin
/WEB-INF/classes/*=Admin
/logs/*=Admin
/__PREVIOUS_VERSION/*=Admin